### ISSUE TITLE
多次单击 检查更新 按钮，关闭 有新版本 和 等待提示 对话框，程序崩溃

### ISSUE THREAD

**Issue by pzhlkj6612** [BesLyric-for-X/BesLyric-for-X#130]
commit: b70eb50811e5f7b99368f0c301c388dbe1d82fc4

debug output:

```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000403fc6 in BesMessageBox::information (title=..., text=..., bWordWrap=<optimized out>) at ...\BesLyric-for-X\BesWidgets\BesMessageBox.cpp:54
54          delete besMessageBox;
(gdb) backtrace
#0  0x0000000000403fc6 in BesMessageBox::information (title=..., text=..., bWordWrap=<optimized out>) at ...\BesLyric-for-X\BesWidgets\BesMessageBox.cpp:54
#1  0x000000000045516b in ThreadCheckUpdate::checkForUpdate (priority=QThread::HighestPriority, muteWhenNoUpdateFound=false, this=0x8b601e8) at .../BesLyric-for-X/Entities/ThreadCheckUpdate.h:41
#2  SuUpgrade::onCheckUpgrade (this=0x8b601a0) at ...\BesLyric-for-X\MiddleWidgets\SettingWidget\SuUpgrade.cpp:110
...
```

code line:

https://github.com/BesLyric-for-X/BesLyric-for-X/blob/b70eb50811e5f7b99368f0c301c388dbe1d82fc4/BesWidgets/BesMessageBox.cpp#L54

**Comment by pzhlkj6612** [comment]
We could use this bug to produce a segment fault to test the mechanism about debugging and crash reporting.

我们可以用这个错误产生一个段错误来检查与调试和错误报告有关的机制。
